package com.computototal.inventario.servicio;

public enum Permiso {
    ADMINISTRAR_USUARIOS,
    ADMINISTRAR_CATALOGOS,
    ELIMINAR_REGISTROS,
    REGISTRAR_EQUIPOS,
    ACTUALIZAR_EQUIPOS,
    REGISTRAR_UBICACIONES,
    ACTUALIZAR_UBICACIONES,
    CAMBIAR_ESTADO_EQUIPO,
    REGISTRAR_INGRESOS,
    REGISTRAR_SALIDAS,
    REGISTRAR_TRASLADOS,
    CAMBIAR_UBICACION_EQUIPO,
    CONFIGURAR_STOCK_MINIMO,
    CONSULTAR_INVENTARIO,
    CONSULTAR_ALERTAS,
    CONSULTAR_HISTORIAL,
    CONSULTAR_REPORTES
}